version: '2.4'

services:
  mosquitto:
    image: eclipse-mosquitto:1.5.3 # 1.5.4 is not taged for arm correctly
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - "./data:/mosquitto/data"
      - "./log:/mosquitto/log"
      - "./:/mosquitto/config"